/* eslint-disable import/prefer-default-export */
export const token =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwY2QwYThkYzI0YmVkNTcyZGExYmRjZSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJreXJ5bG8iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJzdHJpbmciLCJuYmYiOjE2MjQxMTUxNTMsImV4cCI6MTYyNDIwMTU1MywiaXNzIjoiTXlBdXRoU2VydmVyIiwiYXVkIjoiTXlBdXRoQ2xpZW50In0.ySstHMlgGS3kCO0kFElP_Z_CbSwsvxO0qEnf9sSZ6mQ";
